version: '3'
services:
  fim-mysql: # 服务名称
    image: fim-mysql:1.0
    container_name: fim-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai

  fim-backend:
    image: fim-backend:1.0
    container_name: fim-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - fim-mysql

  fim-frontend:
    image: fim-frontend:1.0
    container_name: fim-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fim-mysql
      - fim-backend


